const LOGIN_ERR_MSG = '登录失败，用户名或密码错误！';

const VERIFY_CODE_ERR_MSG = '验证码错误！';

const REGISTER_ERR_MSG = '注册失败！';

const REGISTER_EXIST_MSG = '用户名已存在！';

const LOGIN_SUCCESS_MSG = '登录成功！';

const REGISTER_SUCCESS_MSG = '注册成功！';

const UPDATE_ERR_MSG = '修改失败！';

const UPDATE_SUCCESS_MSG = '修改成功！';

const USER_NOT_FOUND_MSG = '用户不存在！';

const USER_QUERY_ERR_MSG = '获取用户信息失败！';

const USER_QUERY_SUCCESS_MSG = '获取用户信息成功！';

const USER_UPDATE_SUCCESS_MSG = '修改用户信息成功！';

const PWD_ERR_MSG = '旧密码错误！';

const ARTICLE_CATES_SUCCESS_MSG = '获取文章分类成功！';

const ARTICLE_CATES_ERR_MSG = '获取文章分类失败！';

const INSERT_ARTICLE_CATES_ERR_MSG = '新增文章分类失败！';

const ARTICLE_CATES_NOT_FOUND_ERR_MSG = '获取文章分类失败，分类不存在！';

const INSERT_ARTICLE_CATES_EXIST_MSG = '新增文章分类失败，分类名称和别名已存在！';

const INSERT_ARTICLE_CATES_NAME_EXIST_MSG = '新增文章分类失败，分类名称已存在！';

const INSERT_ARTICLE_CATES_ALIAS_EXIST_MSG = '新增文章分类失败，分类别名已存在！';

const UPDATE_ARTICLE_CATES_EXIST_MSG = '修改文章分类失败，分类名称和别名已存在！';

const UPDATE_ARTICLE_CATES_NAME_EXIST_MSG = '修改文章分类失败，分类名称已存在！';

const UPDATE_ARTICLE_CATES_ALIAS_EXIST_MSG = '修改文章分类失败，分类别名已存在！';

const INSERT_ARTICLE_CATES_SUCCESS_MSG = '新增文章分类成功！';

const DELETE_ARTICLE_CATES_SUCCESS_MSG = '删除文章分类成功！';

const DELETE_ARTICLE_CATES_ERR_MSG = '删除文章分类失败！';

module.exports = {
  LOGIN_ERR_MSG,
  VERIFY_CODE_ERR_MSG,
  REGISTER_ERR_MSG,
  REGISTER_EXIST_MSG,
  LOGIN_SUCCESS_MSG,
  REGISTER_SUCCESS_MSG,
  UPDATE_ERR_MSG,
  UPDATE_SUCCESS_MSG,
  USER_NOT_FOUND_MSG,
  USER_QUERY_ERR_MSG,
  USER_QUERY_SUCCESS_MSG,
  USER_UPDATE_SUCCESS_MSG,
  PWD_ERR_MSG,
  ARTICLE_CATES_SUCCESS_MSG,
  ARTICLE_CATES_ERR_MSG,
  INSERT_ARTICLE_CATES_ERR_MSG,
  ARTICLE_CATES_NOT_FOUND_ERR_MSG,
  INSERT_ARTICLE_CATES_EXIST_MSG,
  INSERT_ARTICLE_CATES_NAME_EXIST_MSG,
  INSERT_ARTICLE_CATES_ALIAS_EXIST_MSG,
  UPDATE_ARTICLE_CATES_EXIST_MSG,
  UPDATE_ARTICLE_CATES_NAME_EXIST_MSG,
  UPDATE_ARTICLE_CATES_ALIAS_EXIST_MSG,
  INSERT_ARTICLE_CATES_SUCCESS_MSG,
  DELETE_ARTICLE_CATES_SUCCESS_MSG,
  DELETE_ARTICLE_CATES_ERR_MSG,
}